"""empty message

Revision ID: 616a4a62d3e2
Revises: 
Create Date: 2019-02-03 16:29:46.185410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '616a4a62d3e2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assistantship',
    sa.Column('sid', sa.Integer(), nullable=False),
    sa.Column('term', sa.String(length=2), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('sid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assistantship')
    # ### end Alembic commands ###
